// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeblAwR3Ff_2fXHSr8gon5rGCoeSDQ4mE',
    appId: '1:69540104764:android:3e26a6fdf05ff9ea48d139',
    messagingSenderId: '69540104764',
    projectId: 'emailauth2-933ef',
    storageBucket: 'emailauth2-933ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZoPuDMDxzj9hpUUWmJ7w6r5zsSTn8bs',
    appId: '1:69540104764:ios:3d9799880e1d82b648d139',
    messagingSenderId: '69540104764',
    projectId: 'emailauth2-933ef',
    storageBucket: 'emailauth2-933ef.firebasestorage.app',
    androidClientId: '69540104764-q3l7etj91042rd832loc2pau5cktlpoj.apps.googleusercontent.com',
    iosClientId: '69540104764-bp21d3r9om7745dsl42fsemjbhugql5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskMngmt',
  );
}
